apiVersion: traefik.containo.us/v1alpha1
kind: TraefikService
metadata:
  name: restserver-traefik-service
  namespace: realtime-app

spec:
  weighted:
    services:
      - name: restserver-v1
        port: 8080
        weight: 75
      - name: restserver-v2
        port: 8080
        weight: 25
