FROM node:12.2.0-alpine

LABEL maintainer="Mario Raspiantoro<raspiantoro@gmail.com>"
LABEL REPO="https://github.com/raspiantoro/realtime-web-apps"

WORKDIR /app

ENV PATH /app/node_modules/.bin:$PATH

COPY ./client/web .

RUN npm install

ENTRYPOINT ["npm", "run", "start"]