version: "3"
services:
  envoy:
    container_name: envoy
    image: envoyproxy/envoy:latest
    command: /usr/local/bin/envoy -c /etc/envoy/envoy.yaml
    ports:
      - "9901:9901"
      - "8010:8010"
    volumes:
      - ./envoy.yaml:/etc/envoy/envoy.yaml
    networks:
      streamnet:
        aliases:
          - envoy
  streamserver:
    container_name: streamserver
    build:
      context: .
      dockerfile: server/deployments/Dockerfile
    image: streamserver:latest
    restart: on-failure
    ports:
      - "7070:7070"
    networks:
      streamnet:
        aliases:
          - streamserver
    
networks:
  streamnet: