version: "3"
services:
  envoy:
    container_name: envoy
    image: envoyproxy/envoy:latest
    command: /usr/local/bin/envoy -c /etc/envoy/envoy.yaml
    ports:
      - "9901:9901"
      - "8010:8010"
    volumes:
      - ./envoy.yaml:/etc/envoy/envoy.yaml
    networks:
      streamnet:
        aliases:
          - envoy
  nats-streaming:
    container_name: nats-streaming
    image: nats-streaming
    command: -p 4222 -m 8222 -cid streamapps
    ports:
      - "4222:4222"
      - "4223:4223"
      - "8223:8223"
    networks:
      streamnet:
        aliases:
          - nats-streaming 
  nats-dashboard:
    container_name: nats-dashboard
    image: nats-dashboard
    ports:
      - "8282:8282"
      - "8222:8222"
    environment:
      - STAN_URL=nats://nats-streaming:4222
      - STAN_CLUSTER=streamapps
      - STAN_MONITOR_URL=http://nats-streaming:8222
    networks:
      streamnet:
        aliases:
          - nats-dashboard
  streamserver:
    container_name: streamserver
    build:
      context: .
      dockerfile: server/deployments/Dockerfile
    image: streamserver:latest
    restart: on-failure
    ports:
      - "7070:7070"
    networks:
      streamnet:
        aliases:
          - streamserver
  streamweb:
    container_name: streamweb
    build:
      context: .
      dockerfile: client/web/deployments/Dockerfile
    image: streamweb:latest
    restart: on-failure
    ports:
      - "8080:80"
    networks:
      streamnet:
        aliases:
          - streamweb
    
networks:
  streamnet: