version: "3"
services:
  envoy:
    container_name: envoy
    image: envoyproxy/envoy:v1.12.1
    command: /usr/local/bin/envoy -c /etc/envoy/envoy.yaml
    ports:
      - "9901:9901"
      - "8010:8010"
    volumes:
      - ./envoy.yaml:/etc/envoy/envoy.yaml
    networks:
      streamnet:
        aliases:
          - envoy
  nats-streaming:
    container_name: nats-streaming
    image: nats-streaming
    command: -p 4222 -m 8222 -cid streamapps
    ports:
      - "4222:4222"
      - "4223:4223"
      - "8223:8223"
    networks:
      streamnet:
        aliases:
          - nats-streaming 
  nats-streaming-console:
    container_name: nats-streaming-console
    image: nats-streaming-console
    build:
      context: .
      dockerfile: dockerfile/nats-streaming-console.dockerfile
    ports:
      - "8282:8282"
      - "8222:8222"
    environment:
      - STAN_URL=nats://nats-streaming:4222
      - STAN_CLUSTER=streamapps
      - STAN_MONITOR_URL=http://nats-streaming:8222
    networks:
      streamnet:
        aliases:
          - nats-streaming-console
  streamserver:
    container_name: streamserver
    image: raspiantoro/realtime-streamserver:latest
    restart: on-failure
    ports:
      - "7070:7070"
    environment:
      - GRPC_PORT=7070
      - GRPC_HOST=0.0.0.0
      - NATS_HOST=nats-streaming
      - NATS_PORT=4222
      - NATS_CLIENT_ID=streamappserver
      - NATS_CLUSTER_ID=streamapps
    networks:
      streamnet:
        aliases:
          - streamserver
  streamweb:
    container_name: streamweb
    image: raspiantoro/realtime-web:latest
    restart: on-failure
    ports:
      - "8080:3000"
    environment:
      - REACT_APP_GRPC_PORT=8010
      - REACT_APP_GRPC_HOST=localhost
    networks:
      streamnet:
        aliases:
          - streamweb
  restserver:
    container_name: restserver
    image: raspiantoro/realtime-restserver:latest
    restart: on-failure
    ports:
      - "8081:1234"
    environment:
      - PORT=1234
      - HOST=0.0.0.0
      - NATS_HOST=nats-streaming
      - NATS_PORT=4222
      - NATS_CLIENT_ID=streamapprest
      - NATS_CLUSTER_ID=streamapps
    networks:
      streamnet:
        aliases:
          - restserver
  restserver-v0.1.0:
    container_name: restserver-v0.1.0
    image: raspiantoro/realtime-restserver:v0.1.0
    restart: on-failure
    ports:
      - "8082:1234"
    environment:
      - PORT=1234
      - HOST=0.0.0.0
      - NATS_HOST=nats-streaming
      - NATS_PORT=4222
      - NATS_CLIENT_ID=streamapprestv1
      - NATS_CLUSTER_ID=streamapps
    networks:
      streamnet:
        aliases:
          - restserver
    
networks:
  streamnet:
