apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
  namespace: realtime-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
        - name: web
          image: raspiantoro/realtime-web
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 80
