apiVersion: apps/v1
kind: Deployment
metadata:
  name: restserver-v1
  namespace: realtime-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app:  restserver-v1
  template:
    metadata:
      labels:
        app: restserver-v1
    spec:
      containers:
        - name: restserver-v1
          image: raspiantoro/realtime-restserver:v0.1.0
          resources:
              limits:
                memory: "128Mi"
                cpu: "500m"
          ports:
            - containerPort: 80
          env:
            - name: PORT
              value: "80"
            - name:  HOST
              value: "0.0.0.0"
            - name: NATS_HOST
              value: "stan.realtime-app"
            - name: NATS_PORT
              value: "4222"
            - name: NATS_CLIENT_ID
              value: "restserver-v1"
            - name: NATS_CLUSTER_ID
              value: "streamapps"