version: "3"
services:
  restserver-v1:
    image: raspiantoro/realtime-restserver:v0.1.0
    ports:
      - "8082:1234"
    environment:
      - PORT=1234
      - HOST=0.0.0.0
      - NATS_HOST=nats-streaming
      - NATS_PORT=4222
      - NATS_CLIENT_ID=streamapprestv1
      - NATS_CLUSTER_ID=streamapps
    networks:
      streamnet:
        aliases:
          - restserver-v1
    
networks:
  streamnet:
    external: true