version: "3"
services:
  restserver-v1:
    image: raspiantoro/realtime-restserver:v0.1.0
    environment:
      - PORT=1234
      - HOST=0.0.0.0
      - NATS_HOST=nats-streaming
      - NATS_PORT=4222
      - NATS_CLIENT_ID=streamapprestv1
      - NATS_CLUSTER_ID=streamapps
    networks:
      streamnet:
        aliases:
          - restserver-v1
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.restserver-v1.rule=Host(`rest.realtime`)"
        - "traefik.http.routers.restserver-v1.entrypoints=web"
        - "traefik.http.routers.restserver-v1.service=canary@file"
        - "traefik.http.services.restserver-v1.loadbalancer.server.port=1234"
    
networks:
  streamnet:
    external: true