version: "3"
services:
  restserver-v2:
    image: raspiantoro/realtime-restserver:v0.2.0
    environment:
      - PORT=1234
      - HOST=0.0.0.0
      - NATS_HOST=nats-streaming
      - NATS_PORT=4222
      - NATS_CLIENT_ID=streamapprestv2
      - NATS_CLUSTER_ID=streamapps
    networks:
      streamnet:
        aliases:
          - restserver-v2
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.http.services.restserver-v2.loadbalancer.server.port=1234"
    
networks:
  streamnet:
    external: true