version: "3.3"
services:
  envoy:
    image: envoyproxy/envoy:v1.12.1
    command: /usr/local/bin/envoy -c /etc/envoy/envoy.yaml
    ports:
      - "9901:9901"
      - "8010:8010"
    configs:
      - source: envoy_config
        target: /etc/envoy/envoy.yaml
    networks:
      streamnet:
        aliases:
          - envoy
  streamserver:
    image: raspiantoro/realtime-streamserver:latest
    ports:
      - "7070:7070"
    environment:
      - GRPC_PORT=7070
      - GRPC_HOST=0.0.0.0
      - NATS_HOST=nats-streaming
      - NATS_PORT=4222
      - NATS_CLIENT_ID=streamappserver
      - NATS_CLUSTER_ID=streamapps
    networks:
      streamnet:
        aliases:
          - streamserver

configs:
  envoy_config:
    file: ./envoy.yaml

networks:
  streamnet:
    external: true
