version: "3.3"
services:
  envoy:
    image: envoyproxy/envoy:v1.12.1
    command: /usr/local/bin/envoy -c /etc/envoy/envoy.yaml
    configs:
      - source: envoy_config
        target: /etc/envoy/envoy.yaml
    networks:
      streamnet:
        aliases:
          - envoy
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.streamserver.rule=Host(`stream.realtime`)"
        - "traefik.http.routers.streamserver.entrypoints=web"
        - "traefik.http.services.streamserver.loadbalancer.server.port=8010"

  streamserver:
    image: raspiantoro/realtime-streamserver:latest
    environment:
      - GRPC_PORT=7070
      - GRPC_HOST=0.0.0.0
      - NATS_HOST=nats-streaming
      - NATS_PORT=4222
      - NATS_CLIENT_ID=streamappserver
      - NATS_CLUSTER_ID=streamapps
    networks:
      streamnet:
        aliases:
          - streamserver

configs:
  envoy_config:
    file: ./envoy.yaml

networks:
  streamnet:
    external: true
