log:
  level: DEBUG
  format: json

accessLog:
  format: json
  bufferingSize: 5

providers:
  docker:
    watch: true
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
    swarmMode: true
    network: streamnet
    swarmModeRefreshSeconds: 5
  file:
    directory: /conf.d
    watch: true

api:
  dashboard: true
  insecure: true
  debug: true

entryPoints:
  web:
    address: ":80"
    forwardedHeaders:
      insecure: true
